module Oob_elec
#===================================================
# You can add items to the wire type tab
# !! Warning Array size is limtied to 30 items!!
#===================================================
@@wireTypesTab = [
	#	["label", "nbwires", "wire section/type"], 
		["2 x 1.5 mm2", "2", "1.5"], 
		["3 x 1.5 mm2", "3", "1.5"], 
		["4 x 1.5 mm2", "4", "1.5"], 
		["5 x 1.5 mm2", "5", "1.5"], 
		["7 x 1.5 mm2", "7", "1.5"], 
		["2 x 2.5 mm2", "2", "2.5"], 
		["3 x 2.5 mm2", "3", "2.5"], 
		["5 x 2.5 mm2", "5", "2.5"], 
		["7 x 2.5 mm2", "7", "2.5"], 
		["2 x 6.0 mm2", "2", "6.0"], 
		["3 x 6.0 mm2", "3", "6.0"], 
		["5 x 6.0 mm2", "5", "6.0"], 
		["2 x 10.0 mm2", "2", "10.0"], 
		["3 x 10.0 mm2", "3", "10.0"], 
		["5 x 10.0 mm2", "5", "10.0"], 
		["2 x 16.0 mm2", "2", "16.0"], 
		["3 x 16.0 mm2", "3", "16.0"], 
		["5 x 16.0 mm2", "5", "16.0"], 
		["5 x 35.0 mm2", "5", "35.0"], 
		["1 x RJ 45", "1", "RJ45"],
		["1 x TV", "1", "TV"],
		["1 x Telephone", "1", "Telephone"],
		#AWG
		["4/0 AWG", "1", "107"],
		["3/0 AWG", "1", "85"],
		["2/0 AWG", "1", "67"],
		["8 AWG", 	"1", "8"],
		["8/2 AWG", "2", "8"],
		["8/3 AWG", "3", "8"],
		["10/2 AWG", "2", "10"],
		["10/3 AWG", "3", "10"],
		["12/2 AWG", "2", "12"],
		["12/3 AWG", "3", "12"],
		["14/2 AWG", "2", "14"],
		["14/3 AWG", "3", "14"],
		# German wires
		["NYM-J 3 x 1.5 mm2", "3", "1.5 NYM"],
		["NYM-J 5 x 1.5 mm2", "5", "1.5 NYM"],
		["NYM-J 7 x 1.5 mm2", "7", "1.5 NYM"],
		["NYM-J 3 x 2.5 mm2", "3", "2.5 NYM"],
		["NYM-J 5 x 2.5 mm2", "5", "2.5 NYM"],
		["NYM-J 7 x 2.5 mm2", "7", "2.5 NYM"],
		["NYM-J 5 x 6 mm2", "5", "6.0 NYM"],
		["NYM-J 5 x 10 mm2", "5", "10.0 NYM"],
		["NYM-J 5 x 16 mm2", "5", "16.0 NYM"],
		["NYM-J 5 x 35 mm2", "5", "35.0 NYM"],
		["NYY-J 3 x 1.5 mm2", "3", "1.5 NYY"],
		["NYY-J 5 x 1.5 mm2", "5", "1.5 NYY"],
		["NYY-J 7 x 1.5 mm2", "7", "1.5 NYY"],
		["NYY-J 3 x 2.5 mm2", "3", "2.5 NYY"],
		["NYY-J 5 x 2.5 mm2", "5", "2.5 NYY"],
		["NYY-J 7 x 2.5 mm2", "7", "2.5 NYY"],
		["NYY-J 5 x 6 mm2", "5", "6.0 NYY"],
		["NYY-J 5 x 10 mm2", "5", "10.0 NYY"],
		["NYY-J 5 x 16 mm2", "5", "16.0 NYY"],
		["NYY-J 5 x 35 mm2", "5", "35.0 NYY"],
		["KNX2x2x0.8 YCYM", "4", "0.8 KNX"],
		["Network Cat7 Simplex", "1", "Cat7"],
		["Network Cat7 Duplex",  "2", "Cat7"],
		["Network Cat7a Simplex", "1", "Cat7a"],
		["Network Cat7a Duplex",  "2", "Cat7a"],
	]
	
# Official components should be placed in PLugins/Oob_Elec/components folder
# Custom components should be in PLugins/Oob_Elec/customDevices folder
@@devicesTab = [
		#["label","skp file", "connection type: plug, switch, ceiling, floor, wall, switchboard"]
		["Plug",									"Plug.skp", 								"plug"],
		["Plug 16 A",								"Plug_16A.skp", 							"plug"],
		["Plug x 2",								"Plug_double.skp", 							"plug"],
		["Plug x 3",								"Plug_triple.skp", 							"plug"],
		["TV plug",									"coaxialTV.skp",							"plug"],				
		["RJ45 plug",								"RJ45plug.skp",								"plug"],				
		["Telephone plug",							"telephonePlug.skp",						"plug"],
		["Duplex receptacle GFI",					"Duplex receptacle GFI.skp",				"plug"],			
		["Duplex receptacle WP GFI",				"Duplex receptacle WP GFI.skp",				"plug"],
		["Duplex receptacle",						"Duplex receptacle.skp",					"plug"],			
		["Duplex receptacle Half switched",			"Duplex receptacle Half switched.skp",		"plug"],			
		["Quad receptacle",							"Quad receptacle.skp",						"plug"],	
		["CAT 6 point",								"CAT6point.skp",							"plug"],		
		["CAT 6 dual point",						"CAT6dualpoint.skp",						"plug"],		
		["CAT 6 quad point",						"CAT6quadpoint.skp",						"plug"],		
		["Duplex receptacle recessed on floor",		"Duplex receptacle recessed on floor.skp",	"plug"],
		["Hoven plug",								"HovenPlug.skp", 							"plug"],
		
		["Junction box (floor)",					"Box_7x7.skp",								"floor"],			
		
		["Ceiling light",							"Light.skp",								"ceiling"],
		
		["LED ceiling light",						"LEDlight.skp",								"ceiling"],
		["Junction box (ceiling)",					"Box_7x7ceiling.skp",						"ceiling"],			
		["Ceiling speaker",							"CeilingSpeaker.skp",						"ceiling"],	
		["Fan with light",							"LightFan.skp",								"ceiling"],	
		["Recessed LED housing",					"RecessedLEDlight.skp",						"ceiling"],	
		["2 Inch LED oculus",						"2InchOculusLED.skp",						"ceiling"],	
		["4.5inches LED",							"4.5InchesLED.skp",							"ceiling"],	
		["4.5inches LED Square",					"4.5InchesLEDsquare.skp",					"ceiling"],	
		["Neon tube",								"NeonTube.skp",								"ceiling"],
		
		#13 wall devices
		["Cube light (wall)",						"WallLightSquare.skp",						"wall"],	
		["LED light module (wall)",					"LedLightModule.skp",						"wall"],	
		["Wall light",								"WallLight.skp",							"wall"],		
		
		["Switch Single",							"simple_switch.skp",						"switch"],
		["Switch Double",							"double_switch.skp",						"switch"],			
		["3 gang switches",							"3 gang switches.skp",						"switch"],			
		["4 gang switches",							"4 gang switches.skp",						"switch"],			
		["Key pad",									"keypad.skp",								"switch"],		
		["Door Entry",								"DoorEntry.skp",							"switch"],		
		["Door Bell",								"DoorBell.skp",								"switch"],		
		["Waterproof switch",						"waterproof_switch.skp",					"switch"],		
		
		["Switch board",							"SwitchBoard.skp",							"switchboard"],	
		# new devices 2019
		
		#new devices 2020
		["Touch screen",							"TouchScreen.skp",							"switch"],		
		
	]
	
	
# List of standards for devices (mainly oulets) : 
@@standardsTab = [
	["Type A (USA, Canada, Mexico & Japan)", "Elec type A"],
	["Type B (USA, Canada, Mexico & Japan)", "Elec type B"],
	["Type C (Europe, South America & Asia)", "Elec type C"],
	["Type D (India)", "Elec type D"],
	["Type E (France, Belgium, Poland, Slovakia & the Czech Republic)", "Elec type E"],
	["Type F (Europe & Russia)", "Elec type F"],
	["Type G (United Kingdom, Ireland, Malta, Malaysia & Singapore)", "Elec type G"],
	["Type H (Israel, the West Bank & the Gaza Strip)", "Elec type H"],
	["Type I (Australia, New Zealand, China & Argentina)", "Elec type I"],
	["Type J (Switzerland, Liechtenstein & Rwanda)", "Elec type J"],
	["Type K (Denmark & Greenland)", "Elec type K"],
	["Type L (Italy & Chile)", "Elec type L"],
	["Type M (South Africa)", "Elec type M"],
	["Type N (Brazil )", "Elec type N"],
	["Type O (Thailand)", "Elec type O"],
]
	
@@oobTabStrings = 
	{
	"string1" => 				["FR1","EN1"],
	"Plug" => 					["Prise murale","Plug"],
	"Plug 16 A" => 				["Prise murale 16 A","16 A Plug"],
	"Plug x 2" => 				["Prise murale double","Plug x 2"],
	"Plug x 3" => 				["Prise murale triple","Plug x 3"],
	"Hoven plug" => 			["Prise four (attente)","Oven plug"],
	"LED ceiling light" => 		["Eclairage LED plafond","LED ceiling light"],
	"Ceiling light" => 			["Eclairage plafond","Ceiling light"],
	"Wall light" => 			["Applique murale","Wall light"],
	"Junction box (floor)" => 	["Boite de jonction (sol)","Junction box (floor)"],
	"Junction box (ceiling)" => ["Boite de jonction (plafond)","Junction box (ceiling)"],
	"TV plug" => 				["Prise télé","TV plug"],
	"Switch Single" => 			["Interrupteur simple","Single switch"],
	"SwitchDouble" => 			["Interrupteur double","Double switch"],
	"Switch board" => 			["Tableau électrique","Switch board"],
	"Devices" => 				["Appareillages","Devices"],
	"Bill of materials" => 		["Nomenclature","Bill of materials"],
	"idcircuits" => 			["Circuits","Circuits"],
	"idcircuitnumber" => 		["Nom","Name"],
	"idcircuitdevices" => 		["Appareillages","Nb devices"],
	"idcircuitlength" => 		["Câbles","Nb wires"],
	"idcircuitselect" => 		["Selection","Select"],
	"Device" => 				["Appareil","Device"],
	"Number" => 				["Nombre","Number"],
	"Wires" => 					["Câbles","Wires"],
	"Wirings" => 				["Câbles","Wirings"],
	"Wire types" => 			["Types de câbles","Wire types"],
	"Length" => 				["Longueur","Length"],
	"Non connected devices" => 	["Appareils non connectés","Non connected devices"],
	"Select a device" => 	    ["Sélectionner un appareil","Select a device"],
	"RJ45 plug" => 	    		["Prise RJ45","RJ45 plug"],
	"Telephone plug" => 	    ["Prise téléphone","Telephone plug"],
	"Select" => 	   			["Selection","Select"],
	"Nb Elts" => 	    		["Nomb Elts","Numb Elts"],
	"Cross section" => 	    	["Section","Cross section"],
	"Parameters" => 	    	["Paramètres","Parameters"],
	"Extra length" => 	    	["Longueur suppl. appareil.","Device extra length"],
	"Switch board extra length" =>["Long. suppl. tableau elec","Switch board extra length"],
	"Select a wire type" => 	["Sélectionner un type de câble","Select a wire type"],
	"trialkey1" => 				["Clé d'essai trouvée.","Trial key found"],
	"validkey" => 				["Clé d'activation trouvée.","Valid key found"],
	"trialexperid" => 			["Clé d'activation perimée.","Expired key found"],
	"nokey" => 					["Aucune clé d'activation trouvée.","No key found"],
	"View texts" => 			["Textes","View texts"],
	"View heights" => 			["Détails","View details"],
	"View 2D" => 				["2D","View 2D"],
	"View 3D" => 				["3D","View 3D"],
	"Register now" => 			["Enegistrer","Register now"],
	"License found" => 			["Licence OK","License found"],
	"Display" => 				["Affichage:","Display:"],
	"hautprise" => 				["Hauteur sol-prises standard","Floor-outlets height (default)"],
	#15
	"hautcustom1" => 			["Hauteur custom #1","Custom height #1"],
	"hautcustom2" => 			["Hauteur custom #2","Custom height #2"],
	"hautcustom3" => 			["Hauteur custom #3","Custom height #3"],
	#20 custom 
	"hautcustom4" => 			["Hauteur custom #4","Custom height #4"],
	"hautcustom5" => 			["Hauteur custom #5","Custom height #5"],
	
	"hautinter" => 				["Hauteur sol-interupteurs","Height of switches (from floor)"],
	"hautmur" =>				["Hauteur sol-appliques murales","Height of wall lights (from floor)"],
	
	"hautplafond" => 			["Hauteur plafond","Height of ceiling"],
	"rayoncable" => 			["Rayon câbles","Wire paths radius"],
	"View wires(arc)" => 		["Câbles (arcs)","Wires (arc)"],
	"View wires(dotted lines)" =>["Câbles (lignes)","Wires (dotted lines)"],
	
	"helpstring1" => 			["Cliquer pour positionner l'équipement, touche \"Esc\" pour sortir, touche \"SHIFT\" pour tourner","Click to place device, \"SHIFT\" to turn,  \"Esc\" key to quit"],
	# 2019 devices
	"Ceiling speaker" =>		["Haut parleur plafond","Ceiling speaker"],	
	"Fan with light" =>			["Ventilateur avec luminaire","Fan with light"],	
	"Key pad" =>				["Digicode","Key pad"],	
	"CAT 6 point" =>			["Prise CAT 6","CAT6 point"],		
	"CAT 6 dual point" =>		["Prise double CAT 6","CAT 6 dual point"],		
	"CAT 6 quad point" =>		["Prise quadruple CAT 6","CAT6 quad point"],
	"Door Entry" =>				["Clavier entrée", "Door entry"],
	"Door Bell" =>				["Sonnette","Door bell"],	
		
	# 2020 devices
	"Touch screen" =>			["Ecran tactile", "Touch screen"],
	"Duplex receptacle GFI" =>					["Prise double duplex"			,"Duplex receptacle GFI"	 				],			
	"Duplex receptacle WP GFI"=>				["Prise double étanche"			,"Duplex receptacle WP GFI"					],
	"Duplex receptacle" =>						["Prise double"					,"Duplex receptacle.skp" 					],			
	"Duplex receptacle Half switched"	=>		["Prise double avec interrupteur","Duplex receptacle half switched" 		],	
	"Quad receptacle" =>						["Prise quadruple"				,"Quad receptacle" 							],
	"Duplex receptacle recessed on floor" =>	["Prise double encastrée"		,"Duplex receptacle recessed on floor" 		],
	                                             
	"Recessed LED housing"	=>					["Support LED enastré"			,"Recessed LED housing" 					],	
	"2 Inch LED oculus"	=>						["LED encastrée 5 cms"			,"2 inches LED oculus" 						],	
	"4.5inches LED"=>							["LED 11 cms"					,"4.5 inches LED"  							],		
	"4.5inches LED Square"=>					["LED 11 cms carré"				,"4.5 inches LED Square" 					],		
	"Neon tube"=>								["Tube néon"					,"Neon tube" 								],			
	"Cube light (wall)"=>						["Lampe murale cube"			,"Cube light (wall)" 						],			
	"LED light module (wall)"=>					["Lampe murale rectangle"		,"Rectangle LED light (wall)" 				],

	"Delete custom device"=>							["Supprimer l'équipement custom" 	,"Delete custom device"					],
	"Define a custom device from an existing device" => ["Créer un équipement custom à partir d'un autre", "Define a custom device from an existing device"],
	"define as new custom device" => 					["Définir comme nouvel équipement custom", "Define as new custom device"],
	"unset custom height"=> 							["Annuler la hauteur custom", "unset custom height"],
	#15
	"set custom height 1"=> 							["Assigner hauteur custom #1", "set custom height #1"],
	"set custom height 2"=> 							["Assigner hauteur custom #2", "set custom height #2"],
	"set custom height 3"=> 							["Assigner hauteur custom #3", "set custom height #3"],
	#20
	"set custom height 4"=> 							["Assigner hauteur custom #4", "set custom height #4"],
	"set custom height 5"=> 							["Assigner hauteur custom #5", "set custom height #5"],
	
	# device types
	"plugs"	=> 			["Prises", "Plugs"],
	"switchs"	=> 		["Interrupteurs", "Switches"],
	"ceilings"	=> 		["App. plafond", "Ceiling devices"],
	"floors"	=> 		["App. sol", "Floor devices"],
	"walls"	=> 			["App. muraux", "Wall devices"],
	"switchboards"	=> 	["Tableaux élec.", "Switch boards"],
	
	"Vertical wires" => ["Lignes verticales", "Vertical wires"],
	}
	
end	